language: node_js
sudo: false
dist: bionic
node_js:
- '10'
- '12'
install:
- npm install
- pip install --user awscli
script:
- npm run build-electron
notifications:
  email:
    on_success: never
    on_failure: always
